### ISSUE TITLE
Benchmarks server startup attempts to roll forward from dotnet 5.0 to dotnet 6.0 alpha

### ISSUE THREAD

**Issue by RobertHenry6bev** [aspnet/Benchmarks#1584]
For "net5.0" world during startup, a "master/eng/Versions.props" file is downloaded, which empirically contains references to roll forward to 6.0.0-alpha.  As of now, you can't do that, and get:

05:05:02.850] Job failed on benchmark server, stopping...
Job failed at runtime:
[STDERR] The specified framework 'Microsoft.NETCore.App', version '5.0.0-rc.1.20431.5', apply_patches=1, version_compatibility_range=patch cannot roll-forward to the previously referenced version '6.0.0-alpha.1.20428.2'.

I believe the code near here: https://github.com/aspnet/Benchmarks/blob/6ab4e780e9bc35a21016bd8cac591ec0de1b64d7/src/BenchmarksServer/Startup.cs#L3062
is too aggressive in downloading master/eng/Versions.props file, but should instead download "release/5.0/eng/Versions.props", following the examples in the preceding switch arms.  5.0.0 is now, presumably, stable enough.

Are there other special cases for 5.0.0 that need fixing?  How will this code be maintained for future versions?

**Comment by sebastienros** [comment]
You should use dotnet/crank instead. Bugs will be fixed there. I am not fixing bugs on BenchmarksServer anymore.

There might be a period where some adjustements need to be made, since we are now targetting 6.0 on the master branches. For instance all benchmarks are currently broken since there was a breaking change in the runtime that aspnet hasn't reacted to yet (System.IO.Pipelines is not shipped with the runtime anymore).
