### ISSUE TITLE
Run Fortunes benchmarks for Dapper/EF Core, both platform and non-platform

### ISSUE THREAD

**Issue by roji** [aspnet/Benchmarks#1632]
In the current main TE dashboard, the Fortunes chart shows non-platform EF, non-platform raw, and platform raw.

As we are now working on improving EF Core Fortunes perf to match Dapper, we need to track Dapper there as well. In addition, since a lot of attention has been concentrated on the platform benchmark ("the fastest .NET can do"), we'd like to also track perf for that as well.

So ideally, we'd have two charts - one non-platform with raw/dapper/ef, and one platform with raw/dapper/ef. It would also be great to show EF Core perf in the KPIs dashboard as well, to track the overall improvements done for 6.0.

/cc @sebastienros @ajcvickers

**Comment by sebastienros** [comment]
Can you update the Platform Benchmarks with Dapper and EF implementations?

The idea would be to clone the class `RawDb`, with `DapperDb` and `EFDb`, then with  a conditional compilation flag declare `BenchmarkApplication.Db` as `DapperDb` or `EFDb` instead of `RawDb`. 

We can also add new scenarios that will set the correct flag (EF, Dapper, Raw), as they already define `DATABASE`. The connection string would remain the same. If it should change, then the scenarios would do so too.

**Comment by roji** [comment]
Yeah, I'll do this work - but it will probably take me a bit of time before I get around to it.

**Comment by DamianEdwards** [comment]
This was done
<img width="149" alt="image" src="https://user-images.githubusercontent.com/249088/226053957-bfe462d0-989e-450d-b936-686bdda57255.png">
