### ISSUE TITLE
Could you please add the result of  the combination of IIS8.5 and ASP.net5?

### ISSUE THREAD

**Issue by ForkBug** [aspnet/Benchmarks#27]
Many developers on windows platform may work on this group

**Comment by DamianEdwards** [comment]
I wasn't planning on putting those results in here as they involve running ASP.NET 5 behind IIS. It would be like benchmarking Node behind NGNIX. It's just not something we can really do an awful lot about to improve performance given the mechanics involved. This repo is more concerned with benchmarking the core scenarios.

All that said, I'm happy to add the results from one run of the plaintext benchmark so that there's a reference point.

**Comment by ForkBug** [comment]
Kestrel is a simple server. Too simple, so far.
Asp.net + IIS is described as Node + NGNIX. Does it mean ASP.net team discards IIS?

**Comment by benaadams** [comment]
If you are trying to benchmark Kestrel I imagine you would.

**Comment by gdau** [comment]
Sorry to revive this old issue, but is there a place besides this where we can find a comparison of ASP.NET 5.0 (Core) on IIS vs. ASP.NET 4.x on IIS (I imagine many people will be using this configuration, at least initially, as an upgrade path and would be interested to see what the real-world performance differences might be between their "new" and "old" apps).

**Comment by DamianEdwards** [comment]
We'll go ahead and add results for running all the scenarios behind IIS on Windows and NGNIX on Linux. Perf on the high throughput tests will likely be terrible compared to raw Kestrel, but for the more involved scenarios (e.g. querying DB) it's likely to show the impact is much smaller.
