### ISSUE TITLE
Techempower single/multi query performance

### ISSUE THREAD

**Issue by shravan2x** [aspnet/benchmarks#391]
Most of the benchmarks on this repo are for **plaintext** requests, which ASP.NET Core seems to be good at. In the latest TE benchmarks ([round 15](https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=plaintext)), it seems to be 80.9% of the best solution, which seems like a good result.

However, in almost _every_ other benchmark **single query**/**multi query**/**fortunes**/**data updates**, ASP.NET lags behind at a scary distance - 24.5%, 31.3%, 10.5%, and 27.2% respectively. Even in some of the newer issues like #382, ASP seems to be focusing on the plaintext benchmarks, which are reasonable indicators of performance, but more than likely not what ASP.NET Core is mainly used for.

My main development stack being ASP, it hurts to see it this way. But even worse, it feels like the README on the official benchmarks repo (this one) misrepresents the actual performance of ASP.NET Core by including only its best scenarios. Could we include these other benchmarks as well so new users are not misled?

P.S. I'd also like to know what causes this massive gap in performance, if possible.

**Comment by sebastienros** [comment]
> Most of the benchmarks on this repo are for plaintext requests

I think we have many scenarios for database access. And we are actually putting most of our efforts on these. So be reassured that we are not ignoring it at all.

Some things you should know:
1- The database numbers don't reflect our current state when looking at the physical results, because TE is using an uncommon number of cores (40 physical cores). We have already found a solution for this issue, which will be public with they next batch of results
2- We are actually better when displaying the Azure results which use a more common server type, unfortunately they have stopped measuring it on Azure for the past year. They will release a new set of benchmarks for Azure in the next couple of weeks.
3- I have submitted a PR that uses better settings for the database access. It improves all the benchmarks from 10% (EF) to 65% (single query).
4- The most important point, between .NET Core 2.1 improvements and by engaging with the ADO.NET providers developers, we are increasing the benchmarks by a huge margin (worst case is 50%). And this applies to PostgreSql, MySql, Sqlite and Sql Server providers. Unfortunately these updates will only be available when the respective packages are on Nuget, and most probably in the next TE results. But all existing applications should be able to perform much better without any code change on developers' side.

A last not that we are measuring these numbers every single day, and looking at how we can make improvements. This is really paying off and the next TE benchmarks should show it.

If there are specific scenarios you think we should also track as they are showing some bad results then please file other issues.

**Comment by shravan2x** [comment]
Are there plans to include these benchmarks in the README once these changes go through?

**Comment by sebastienros** [comment]
I personally like the idea of relying on an independent third party to display comparative numbers, in this case Tech Empower. We will probably remove this table from our readme and favor links to TE and also our internal PBI dashboard: https://aka.ms/aspnet/benchmarks. This dashboard will be updated to provide a more simplified view for dotnet core users. Right now it's raw data without much context which is not very useful for the public. 

And these numbers don't include our ADO.NET performance updates yet.

**Comment by shravan2x** [comment]
> I personally like the idea of relying on an independent third party to display comparative numbers, in this case Tech Empower. We will probably remove this table from our readme and favor links to TE and also our internal PBI dashboard

I agree with this. Removing the plaintext readme for direct links to TE would be a good solution.
