### ISSUE TITLE
Test on dual-socket machine

### ISSUE THREAD

**Issue by benaadams** [aspnet/benchmarks#56]
Prior to submitting to Techempower - dual sockets with NUMA have different performance characteristics and Techempower runs the peak benchmark on a dual socket machine (40 HT cores)

**Comment by benaadams** [comment]
Related https://github.com/aspnet/KestrelHttpServer/issues/650

**Comment by SajayAntony** [comment]
@benaadams   :+1: We need to get this sorted out for before submitting for TechEmpower.

**Comment by benaadams** [comment]
If you need an easy test-bed; I do see the behaviour on Azure dual sockets - so a G4 (16 cores 1 socket) has better performance than a G5 (32 cores 2 sockets)

Make sure you switch RSS on on the NIC though as it isn't always on by default - and going via the public end point/ip is faster than going via the VNet local IPs for some reason (e.g. if you have 2 G4s hitting each other, one linux `wrk` one win `kestrel`)

**Comment by SajayAntony** [comment]
Yes we hit this yesterday on our rig and are going after this actively since this definitely is a blocker to submitting to TechEmpower.  @nathana1 is on this with the CLR perf folks to get this sorted out. There are multiple variables here with how Kestrel's+ThreadPool+GC behaves with the corresponding numa config. Also we need to take care of this on Windows and Linux.

**Comment by bhauer** [comment]
Due to circumstances outside of our control, we (TechEmpower) will no longer have access to the dual Xeon E5 (40 HT core) servers after Round 12.  They are being decommissioned imminently and will not be replaced.  [We need to build a new hardware environment.](https://groups.google.com/d/msg/framework-benchmarks/IiDBC6l1QuQ/gDyw6OR4BwAJ)

I mention this just as a heads-up.  Doing testing on NUMA is definitely worthwhile for your efforts regardless.

**Comment by benaadams** [comment]
@bhauer I've had good results with Azure G4 VMs (16 Cores Intel Xeon E5 v3, though would probably want to go GS now they are available) which can happily do 12+Gbps between 2 VMs (caveats mentioned above)

The GS5 are the 32 Core variant; essentially a dedicated machine; and [meant to do 20Gbps](https://azure.microsoft.com/en-us/blog/azure-has-the-most-powerful-vms-in-the-public-cloud/); but I haven't managed to get there. They are also NUMA machines; which have additional complexities and I haven't investigated too deeply - just observed the effect.

However, while these are very peak hardware, they are also different to dedicated hardware on a dedicated network so may not suit your needs. Alas I'm not in a position to offer any replacement; just my observations as an outside participant.

/cc @DamianEdwards @shanselman

**Comment by SajayAntony** [comment]
@bhauer Thanks for the update. The NUMA issue is definitely something we want to fix not just for TechEmpower. We are not currently hitting the 64L limit but I suspect we might have to do that also at some point.
