### ISSUE TITLE
Benchmark Server needs to be able to update dotnet

### ISSUE THREAD

**Issue by rynowak** [aspnet/benchmarks#87]
Our workload project files use wildcarding to specify their version of the SDK/runtime https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/project.json#L25

This means that the version our projects need is dependent on our feeds. This also means that the local copy of dotnet on the server can get out of date with what we need to build/run our workload projects.

We need a solution so that every time we take a new CLI it doesn't hose the benchmark server

**Comment by mikeharder** [comment]
I think we can use a method similar to the CI machine.  When running a server job:

1. Use KoreBuild to download the current CLI to a temporary directory.
2. Run dotnet from the temporary directory rather than %ProgramFiles% or %LocalAppData%.
3. Configure the NuGet package cache to use a clean temporary directory.
4. Use a different copy of dotnet.exe to run BenchmarksServer itself.

**Comment by mspandit** [comment]
@rynowak, I think you mean https://github.com/aspnet/benchmarks/blob/c4648450a249a522cf8dc00942a799acaa15b312/src/Benchmarks/project.json#L25
